name: sendy
description: Delivery application in French and Arabic
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase - all compatible versions
  firebase_core: ^3.8.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.1
  firebase_messaging: ^15.2.1
  cloud_functions: ^5.2.1
  firebase_app_check: ^0.3.2+10
  lottie: ^3.1.2
  
  # UI
  font_awesome_flutter: ^10.7.0
  intl_phone_field: ^3.2.0
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # State Management
  provider: ^6.1.1
  
  # UI & Localization
  flutter_localizations:
    sdk: flutter
  
  # Notifications
  flutter_local_notifications: ^18.0.1

  cached_network_image: ^3.3.0
  
  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.12.0
  path_provider: ^2.1.2
  
  # Image Picker
  image_picker: ^1.0.7
  
  # URL Launcher
  url_launcher: ^6.2.4

  # Utilities
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  
# App Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#FF5722"
  adaptive_icon_foreground: "assets/icons/sendy_logo_foreground.png"

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/animation.json